### ISSUE TITLE
File missing

### ISSUE THREAD

**Issue by sdsy888** [bgshih/seglink#4]
Hi, thank you for sharing your code.
However, when I try to do experiment  using the code, I found that the `/seglink/src/` folder is missing which should contains `model_vgg16.py`

Then I found [this](https://github.com/bgshih/vgg16.tf/blob/master/src/model_vgg16.py) on your github.
But it won't work. Seems like this model_vgg16 is not compatatible with that project.
Could you check and give me some advice? Thank you.

**Comment by BowieHsu** [comment]
@sdsy888 The model_vgg16.py is now named model_cnn.py, you can find it under "seglink" folder.

**Comment by sdsy888** [comment]
Yes, thank you!
I found it and some other parts also need to be modified.

**Comment by BowieHsu** [comment]
@sdsy888 i have uploaded converted checkpoint, link: https://pan.baidu.com/s/1nvuWqlr password: isme, may it can save your time

**Comment by sdsy888** [comment]
@BowieHsu 
Roger that! Thank you!
